name: Check and Lint

'on':
  pull_request:
    types: [opened, ready_for_review]

env:
  HUSKY: 0

jobs:
  check_and_lint:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - run: npm ci

      - name: Lint
        run: npm run lint

      - name: Check
        run: npm run check
